### ISSUE TITLE
Can add "empty" cards

### ISSUE THREAD

**Issue by evajurman** [pokemon-tcg/deck-builder#4]
Not a feature
Is a bug
![image](https://cloud.githubusercontent.com/assets/1131494/13713302/5bdbabee-e796-11e5-9fc2-d6f30cbbaff5.png)

**Comment by kristenmills** [comment]
Oh well it used to prevent you from doing that....

**Comment by kristenmills** [comment]
https://github.com/kristenmills/pokemon-deck-builder/blob/master/src/js/components/pokemon-add.jsx#L87 Missed one this.state.set

**Comment by evajurman** [comment]
Still happens when you change the quantity.

**Comment by kristenmills** [comment]
I know. I noticed yesterday.
